### ISSUE TITLE
Unable to see updates when 'Get Updates' button is clicked

### ISSUE THREAD

**Issue by vswaroop186** [brookspeppin/WorkspaceONE#4]
Hi Brooks,
When i Select 2004, 1909 or 1903 and click on 'Get Updates' button, nothing happens and i dont see any updates on the screen below and that space is blank.
![image](https://user-images.githubusercontent.com/82854043/115325239-98926d00-a1ce-11eb-8428-fb452e608d92.png)

However, get updates works for 1809.
![image](https://user-images.githubusercontent.com/82854043/115325500-12c2f180-a1cf-11eb-945b-2d54b15d4aa9.png)

**Comment by brookspeppin** [comment]
@vswaroop186  The issue should be fixed now with version 1.1
